### ISSUE TITLE
Add support for toollabs

### ISSUE THREAD

**Issue by bd808** [wikimedia/FirefoxWikimediaDebug#2]
See https://gerrit.wikimedia.org/r/#/c/205495/

> &lt;YuviPanda>	ori: is the debug mode http header documented somewhere?
> &lt;      ori>	https://wikitech.wikimedia.org/wiki/Debugging_in_production
> &lt;YuviPanda>	wheeee
> ...
> &lt;YuviPanda>	ori: toollabs supports it too now :D
> &lt;YuviPanda>	X-Wikimedia-Debug
> &lt;      ori>	awesome!
> &lt;YuviPanda>	ori: yeah, earlier if you had a 500 it would give you a generic page, now it’ll give you the actual 500 page

**Comment by bd808** [comment]
@yuvipanda can you give a list of the wildcard domains that this covers?

**Comment by yuvipanda** [comment]
@bd808 tools.wmflabs.org and tools-static.wmflbas.org I'd say.
